import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import MobileBottomNav from "@/components/mobile-bottom-nav";
import SessionInfo from "@/components/SessionInfo"; // 👈 client component
import SessionGate from "@/components/SessionGate"; // 👈 client component
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="...">
        <Providers>
          <SessionGate>
            <SessionInfo />
            <main className="mx-auto max-w-md px-4 pb-24 pt-4 space-y-4">
              {children}
            </main>
            <MobileBottomNav />
          </SessionGate>
        </Providers>
      </body>
    </html>
  );
}
